<script setup>
import{computed,nextTick,onBeforeUnmount,onMounted,ref,watch}from'vue';import{RouterLink}from'vue-router';import L from'leaflet';import'leaflet/dist/leaflet.css'
import{getPlaces}from'../../services/placesApi';import{getFestivalList}from'../../services/festivalsApi';import{placeTypeLabel,toApiCategory}from'../../utils/placeFilters';import{filterIconFor,leafletIconFor}from'../../utils/mapAssets'
const mapRef=ref(null),selectedFilter=ref('전체'),filters=['전체','축제','관광지','문화시설','쇼핑','체험'],allPlaces=ref([]),filteredPlaces=computed(()=>allPlaces.value);let map,markers=[]
const fallback=f=>f.filter(x=>typeof x.lat==='number'&&typeof x.lng==='number').map(x=>({id:x.id,name:x.title,type:x.category,lat:x.lat,lng:x.lng}))
async function load(){try{const p={page:1,size:200},c=toApiCategory(selectedFilter.value);if(c)p.category=c;const page=await getPlaces(p);allPlaces.value=page.items.filter(x=>typeof x.lat==='number'&&typeof x.lng==='number');if(!allPlaces.value.length)allPlaces.value=fallback(await getFestivalList({page:1,size:200}))}catch{allPlaces.value=fallback(await getFestivalList({page:1,size:200}).catch(()=>[]))}}
function render(){if(!map)return;markers.forEach(m=>m.remove());markers=filteredPlaces.value.map(p=>L.marker([p.lat,p.lng],{icon:leafletIconFor(placeTypeLabel(p))}).addTo(map).bindPopup(`<strong>${p.name}</strong><br>${placeTypeLabel(p)}`));requestAnimationFrame(()=>map?.invalidateSize())}
onMounted(async()=>{await nextTick();map=L.map(mapRef.value).setView([37.5665,126.978],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors'}).addTo(map);await load();render()});watch(selectedFilter,async()=>{await load();render()});watch(filteredPlaces,render);onBeforeUnmount(()=>map?.remove())
</script>
<template><section class="map-section section-card"><header><h2>지도에서 찾기</h2><RouterLink to="/map">전체 지도 ›</RouterLink></header><div ref="mapRef" class="map-box"></div><div class="filter-row"><button v-for="f in filters" :key="f" :class="{active:selectedFilter===f}" @click="selectedFilter=f"><img :src="filterIconFor(f)" alt=""><span>{{ f }}</span></button></div></section></template>
<style scoped>
.map-section{padding:16px;border-radius:18px}.map-section header{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}.map-section h2{margin:0;font-size:20px}.map-section header a{font-size:12px;color:#6b756f}.map-box{width:100%;height:292px;border:1px solid #e1e3dc;border-radius:14px;overflow:hidden}.filter-row{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;padding-top:12px}.filter-row button{display:flex;min-width:0;align-items:center;justify-content:center;gap:6px;padding:8px 5px;border:0;border-radius:99px;background:#fff;color:#4d5c54;font-size:10px;font-weight:800}.filter-row button.active{background:#edf6e5;color:#4f982b}.filter-row img{width:24px;height:24px;object-fit:contain}.filter-row span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}@media(max-width:420px){.filter-row{grid-template-columns:repeat(2,1fr)}}
</style>
