<script setup>
import{computed,nextTick,onBeforeUnmount,onMounted,ref,watch}from'vue';import{useRoute}from'vue-router';import L from'leaflet';import'leaflet/dist/leaflet.css'
import{getFestivalById,getFestivalNearby}from'../services/festivalsApi';import{getPlaces}from'../services/placesApi';import{filterIconFor,leafletIconFor}from'../utils/mapAssets'
const route=useRoute(),mapEl=ref(null),festival=ref(null),loading=ref(true),errorMessage=ref(''),nearbyPlaces=ref([]),nearbyLoading=ref(false),nearbyErrorMessage=ref(''),selectedNearbyCategory=ref('전체'),selectedPlace=ref(null),nearbyCategories=['전체','관광지','문화시설','쇼핑'];let map,festivalMarker,nearbyMarkers=[]
const filtered=computed(()=>selectedNearbyCategory.value==='전체'?nearbyPlaces.value:nearbyPlaces.value.filter(p=>p.category===selectedNearbyCategory.value))
function dist(a,b,c,d){const r=x=>x*Math.PI/180,x=r(c-a),y=r(d-b),z=Math.sin(x/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(y/2)**2;return 6371*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
function select(p){selectedPlace.value=p;map?.flyTo([p.lat,p.lng],16);nearbyMarkers.find(m=>m.placeId===p.id)?.openPopup()}
function render(){if(!festival.value||!mapEl.value)return;const{lat,lng,name}=festival.value;if(typeof lat!=='number'||typeof lng!=='number')return;if(!map){map=L.map(mapEl.value).setView([lat,lng],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors'}).addTo(map)}festivalMarker?.remove();festivalMarker=L.marker([lat,lng],{icon:leafletIconFor('축제')}).addTo(map).bindPopup(name);nearbyMarkers.forEach(m=>m.remove());nearbyMarkers=filtered.value.filter(p=>typeof p.lat==='number'&&typeof p.lng==='number').map(p=>{const m=L.marker([p.lat,p.lng],{icon:leafletIconFor(p.category)}).addTo(map).bindPopup(`<strong>${p.title}</strong><br>${p.category}`);m.placeId=p.id;return m});if(nearbyMarkers.length)map.fitBounds(L.featureGroup([festivalMarker,...nearbyMarkers]).getBounds(),{padding:[35,35],maxZoom:15});requestAnimationFrame(()=>map?.invalidateSize())}
async function loadNearby(){nearbyLoading.value=true;try{let items=(await getFestivalNearby(route.params.id,{radiusKm:5,categories:['관광지','문화시설','쇼핑'],limit:12})).items;if(!items.length){const page=await getPlaces({page:1,size:200});items=page.items.filter(p=>['관광지','문화시설','쇼핑'].includes(p.type)&&typeof p.lat==='number').map(p=>({...p,title:p.title||p.name,category:p.type,distanceKm:dist(festival.value.lat,festival.value.lng,p.lat,p.lng)})).filter(p=>p.distanceKm<=5).slice(0,12)}nearbyPlaces.value=items;selectedPlace.value=items[0]||null}catch(e){nearbyErrorMessage.value=e.message||'주변 장소를 불러오지 못했습니다.'}finally{nearbyLoading.value=false}}
async function load(){loading.value=true;try{festival.value=await getFestivalById(route.params.id);await loadNearby()}catch(e){festival.value=null;errorMessage.value=e.message}finally{loading.value=false}await nextTick();render()}
onMounted(load);watch(()=>route.params.id,load);watch(filtered,async()=>{await nextTick();render()});onBeforeUnmount(()=>map?.remove())
</script>
<template><main v-if="loading" class="container state">축제 정보를 불러오는 중입니다.</main><main v-else-if="festival" class="detail-page"><div class="container"><nav><RouterLink to="/">홈</RouterLink> › <RouterLink to="/festivals">축제 캘린더</RouterLink> › 축제 상세</nav><section class="hero"><div class="photo"><img v-if="festival.imageUrl" :src="festival.imageUrl" :alt="festival.name"><span v-else>이미지 준비중</span></div><div class="info"><h1>{{festival.name}}</h1><p><b>기간</b>{{festival.period}}</p><p><b>장소</b>{{festival.place}}</p><p><b>분류</b>{{festival.category}}</p></div></section><section class="location"><div class="map-panel section-card"><h2>축제 위치 및 주변 정보</h2><p>축제와 주변 추천 장소를 지도에서 함께 확인할 수 있어요.</p><div ref="mapEl" class="map"></div></div><aside class="selected section-card"><h3>선택한 장소</h3><template v-if="selectedPlace"><img :src="filterIconFor(selectedPlace.category)" alt=""><h2>{{selectedPlace.title}}</h2><b>{{selectedPlace.category}}</b><p>{{selectedPlace.address}}</p><strong>{{selectedPlace.distanceKm?.toFixed(2)??'-'}}km</strong></template></aside></section><section class="nearby section-card"><header><div><h2>주변 추천 장소 🌿</h2><p>축제 반경 5km 이내 장소</p></div><div class="filters"><button v-for="c in nearbyCategories" :key="c" :class="{active:selectedNearbyCategory===c}" @click="selectedNearbyCategory=c"><img :src="filterIconFor(c)" alt="">{{c}}</button></div></header><div v-if="!nearbyLoading&&filtered.length" class="grid"><button v-for="p in filtered" :key="p.id" @click="select(p)"><div><img :src="filterIconFor(p.category)" alt=""><b>{{p.category}}</b></div><h3>{{p.title}}</h3><p>{{p.distanceKm?.toFixed(2)??'-'}}km</p><small>{{p.address}}</small></button></div><p v-else class="empty">{{nearbyLoading?'불러오는 중...':nearbyErrorMessage||'추천 장소가 없습니다.'}}</p></section></div></main><main v-else class="container state">{{errorMessage||'축제를 찾을 수 없습니다.'}}</main></template>
<style scoped>
.detail-page{padding:22px 0 55px;background:#fffcf7}.detail-page nav{margin:10px 0 28px;color:#7d8780;font-size:13px}.hero{display:grid;grid-template-columns:1fr 1fr;min-height:390px;overflow:hidden;border:1px solid #e3e4d6;border-top:3px solid #69b62f;border-radius:28px;background:#fff}.photo{display:grid;place-items:center;background:#edf5e6}.photo img{width:100%;height:100%;object-fit:cover}.info{display:flex;flex-direction:column;justify-content:center;padding:45px}.info h1{font-size:36px}.info p{display:grid;grid-template-columns:70px 1fr;font-size:14px}.location{display:grid;grid-template-columns:2fr 1fr;gap:20px;margin-top:24px}.map-panel,.selected,.nearby{padding:22px}.map-panel h2,.nearby h2{margin:0 0 5px;font-size:20px}.map-panel>p,.nearby header p{margin:0 0 14px;color:#69746c;font-size:12px}.map{height:430px;border-radius:17px}.selected>img{display:block;width:70px;height:70px;margin:25px auto;object-fit:contain}.selected h2{font-size:17px}.selected>b{padding:4px 8px;border-radius:99px;background:#e9f3ff;font-size:10px}.selected p{font-size:12px}.nearby{margin-top:24px}.nearby header{display:flex;align-items:end;justify-content:space-between}.filters{display:flex;gap:6px}.filters button{display:flex;align-items:center;gap:4px;padding:7px 10px;border:1px solid #d8e2d2;border-radius:99px;background:#fff;font-size:10px}.filters button.active{background:#5eae32;color:#fff}.filters img{width:18px;height:18px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:18px}.grid>button{padding:0 12px 12px;border:1px solid #e2e5dc;border-radius:16px;background:#fff;text-align:left}.grid>button>div{position:relative;display:grid;height:110px;place-items:center;background:#edf5e7;margin:0 -12px 10px;border-radius:16px 16px 0 0}.grid>button>div img{width:48px;height:48px}.grid>button>div b{position:absolute;top:8px;left:8px;font-size:9px}.grid h3{overflow:hidden;font-size:13px;text-overflow:ellipsis;white-space:nowrap}.grid p,.grid small{color:#737d76;font-size:10px}.empty,.state{padding:40px;text-align:center}@media(max-width:850px){.hero,.location{grid-template-columns:1fr}.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:540px){.grid{grid-template-columns:1fr}.filters{overflow:auto;max-width:100%}}
</style>
