<script setup>
import {computed,nextTick,onBeforeUnmount,onMounted,ref,watch} from 'vue'
import L from 'leaflet';import 'leaflet/dist/leaflet.css'
import {getPlaces} from '../services/placesApi';import {getFestivalList} from '../services/festivalsApi';import {placeTypeLabel} from '../utils/placeFilters'
import {filterIconFor,leafletIconFor} from '../utils/mapAssets'
import mapHero from '../assets/ui/map-hero.webp';import tipMascot from '../assets/ui/tip-mascot.webp'
const mapRef=ref(null),selectedFilter=ref('전체'),searchInput=ref(''),searchQuery=ref(''),places=ref([]),loading=ref(false),errorMessage=ref(''),activePlaceId=ref(''),visibleCount=ref(7)
const filters=['전체','축제','공연','전시','체험','전통','야외 행사','관광지','문화시설','쇼핑'];const markerMap=new Map();let map=null,markers=[]
function normalizedType(p){const s=`${placeTypeLabel(p)} ${p.name}`;if(/축제|페스티벌/.test(s))return'축제';if(/공연|음악|콘서트|연극|뮤지컬/.test(s))return'공연';if(/전시|미술|페어|박람회/.test(s))return'전시';if(/체험|레포츠|워크숍/.test(s))return'체험';if(/전통|한옥|궁/.test(s))return'전통';if(/야외|공원|광장|분수/.test(s))return'야외 행사';return placeTypeLabel(p)}
const filteredPlaces=computed(()=>places.value.filter(p=>(selectedFilter.value==='전체'||normalizedType(p)===selectedFilter.value)&&(!searchQuery.value||`${p.name} ${p.address||''}`.toLowerCase().includes(searchQuery.value.toLowerCase()))))
const visiblePlaces=computed(()=>filteredPlaces.value.slice(0,visibleCount.value))
const festivalFallback=a=>a.filter(x=>typeof x.lat==='number'&&typeof x.lng==='number').map(x=>({id:`festival-${x.id}`,name:x.title,type:x.category||'축제공연행사',lat:x.lat,lng:x.lng,address:x.place,start:x.start,end:x.end,imageUrl:x.imageUrl}))
async function loadPlaces(){loading.value=true;try{const[p,f]=await Promise.all([getPlaces({page:1,size:200}),getFestivalList({page:1,size:100})]);places.value=[...p.items.filter(x=>typeof x.lat==='number'&&typeof x.lng==='number'),...festivalFallback(f)]}catch(e){try{places.value=festivalFallback(await getFestivalList({page:1,size:100}))}catch{errorMessage.value=e.message||'장소 데이터를 불러오지 못했습니다.'}}finally{loading.value=false}}
function focusPlace(p){activePlaceId.value=p.id;map?.flyTo([p.lat,p.lng],15,{duration:.65});markerMap.get(p.id)?.openPopup()}
function renderMarkers(){if(!map)return;markers.forEach(m=>m.remove());markerMap.clear();markers=filteredPlaces.value.map(p=>{const m=L.marker([p.lat,p.lng],{icon:leafletIconFor(normalizedType(p))}).addTo(map).bindPopup(`<strong>${p.name}</strong><br>${normalizedType(p)}<br>${p.address||''}`);m.on('click',()=>activePlaceId.value=p.id);markerMap.set(p.id,m);return m});requestAnimationFrame(()=>{map?.invalidateSize();if(markers.length>1)map.fitBounds(L.featureGroup(markers).getBounds(),{padding:[30,30],maxZoom:14})})}
onMounted(async()=>{await nextTick();map=L.map(mapRef.value).setView([37.5665,126.978],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors'}).addTo(map);await loadPlaces();renderMarkers()})
watch(filteredPlaces,()=>{activePlaceId.value='';visibleCount.value=7;renderMarkers()});onBeforeUnmount(()=>map?.remove())
</script>
<template><main class="map-page"><section class="map-hero container"><div><h1>지도 탐색 <span>●</span></h1><p>서울 곳곳의 축제와 명소를 지도에서<br>유형별로 탐색해보세요.</p></div><form class="search" @submit.prevent="searchQuery=searchInput.trim()"><span>⌕</span><input v-model="searchInput" placeholder="지역, 축제, 장소를 검색해보세요"><button>⌕</button></form><img class="hero-art" :src="mapHero" alt=""></section>
<section class="container explorer section-card"><div class="filters"><button v-for="f in filters" :key="f" :class="{active:selectedFilter===f}" @click="selectedFilter=f"><img :src="filterIconFor(f)" alt="">{{ f }}</button></div><div class="layout"><div ref="mapRef" class="map-box"></div><aside class="list-panel"><header><h2>표시 목록</h2><b>{{ filteredPlaces.length }}개</b></header><ul><li v-for="p in visiblePlaces" :key="p.id"><button :class="{active:activePlaceId===p.id}" @click="focusPlace(p)"><div class="place-image"><img v-if="p.imageUrl" :src="p.imageUrl" alt=""><img v-else :src="filterIconFor(normalizedType(p))" alt=""></div><div><p><img :src="filterIconFor(normalizedType(p))" alt=""><strong>{{ p.name }}</strong><em>{{ normalizedType(p) }}</em></p><small>⌖ {{ p.address||'서울' }}</small></div></button></li></ul><p v-if="loading" class="state">불러오는 중...</p><p v-else-if="!visiblePlaces.length" class="state">{{ errorMessage||'검색 결과가 없습니다.' }}</p><button v-if="visibleCount<filteredPlaces.length" class="more" @click="visibleCount+=7">더 많은 장소 보기⌄</button></aside></div></section><aside class="container tip"><img :src="tipMascot" alt=""><p><strong>팁!</strong> 원하는 장소를 클릭하면 상세 정보를 확인할 수 있어요.</p></aside></main></template>
<style scoped>
.map-page{padding:24px 0 40px;background:#fffcf7}.map-hero{display:grid;grid-template-columns:.72fr 1fr 1.18fr;align-items:center;min-height:165px}.map-hero h1{margin:0;font-size:40px}.map-hero h1 span{color:#64ae3b}.map-hero p{font-size:14px;line-height:1.7}.search{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:10px;padding:5px 6px 5px 17px;border:1px solid #ddd;border-radius:99px;background:#fff}.search input{min-width:0;border:0;outline:0}.search button{width:48px;height:48px;border:0;border-radius:50%;color:#fff;background:#62ad37}.hero-art{width:100%;height:155px;object-fit:contain}.explorer{padding:20px;border-radius:24px}.filters{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:18px}.filters button{display:flex;align-items:center;gap:7px;padding:9px 14px;border:0;border-radius:99px;background:#fbfaf7;font-size:12px;font-weight:800}.filters img{width:21px;height:21px;object-fit:contain}.filters button.active{background:#edf6e5;color:#4f982b}.layout{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(340px,1fr);gap:18px}.map-box,.list-panel{height:610px;border:1px solid #e5e4de;border-radius:17px;overflow:hidden}.list-panel{display:flex;flex-direction:column;background:#fff}.list-panel header{display:flex;gap:9px;padding:15px;border-bottom:1px solid #eee}.list-panel h2{margin:0;font-size:16px}.list-panel ul{flex:1;margin:0;padding:0;overflow:auto;list-style:none}.list-panel li{border-bottom:1px solid #eee}.list-panel li>button{display:grid;width:100%;grid-template-columns:80px 1fr;gap:12px;padding:9px 14px;border:0;background:#fff;text-align:left}.list-panel li>button.active{background:#f5faf1}.place-image{display:grid;width:80px;height:68px;place-items:center;border-radius:10px;background:#edf5e7;overflow:hidden}.place-image img:first-child{width:100%;height:100%;object-fit:cover}.place-image img:last-child{width:38px;height:38px;object-fit:contain}.list-panel li>button>div+div{display:flex;min-width:0;flex-direction:column;justify-content:center}.list-panel p{display:flex;align-items:center;gap:6px;margin:0}.list-panel p img{width:18px;height:18px}.list-panel strong{overflow:hidden;font-size:13px;text-overflow:ellipsis;white-space:nowrap}.list-panel em{padding:3px 6px;border-radius:99px;background:#e9f2ff;font-size:9px;font-style:normal}.list-panel small{color:#778079;font-size:10px}.state{margin:auto;text-align:center}.more{margin:10px auto;padding:8px 40px;border:1px solid #ddd;border-radius:99px;background:#fff}.tip{display:flex;align-items:center;gap:13px;margin-top:15px;padding:10px 22px;border:1px solid #dfe8d8;border-radius:15px}.tip img{width:56px;height:56px;object-fit:contain}.tip p{font-size:12px}@media(max-width:1020px){.map-hero{grid-template-columns:1fr 1.5fr}.hero-art{display:none}.layout{grid-template-columns:1fr}}@media(max-width:680px){.map-hero{grid-template-columns:1fr;gap:12px}.filters{flex-wrap:nowrap;overflow:auto}.map-box{height:360px}.list-panel{height:500px}}
</style>
